name: Tests workflow
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
jobs:
  build:
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      MNEMONIC: ${{ secrets.MNEMONIC }}
    name: Build application
    runs-on: ubuntu-latest
    container: node:14
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build

  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    container: node:14
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint sources
        run:
          npm run lint

  unit_test:
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      MNEMONIC: ${{ secrets.MNEMONIC }}
    name: Unit tests
    runs-on: ubuntu-latest
    container: node:14
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Create types
        run: npm run typechain
      - name: Run tests
        run: npm run test
